### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ddrinka** [cmrigney/node-sftp-s3#13]
Tests are failing with the following exception:

```
  1) SFTP Should Write and Read and Delete Correctly:
     Uncaught TypeError: Cannot read property '_log' of undefined
      at lib/node-sftp-s3.js:29:2873
      at test/s3stub.js:99:28
```

**Comment by ddrinka** [comment]
@cmrigney I've never actually worked with Node before.  I'm just hacking along the best I can with my meager javascript skills.  I don't have a Node install running--I have Docker Hub build the docker image and run it on Amazon ECS.

So I don't really know where to start on tracking down why the test is failing.  _log is defined in node-sftp-s3.js as a class method.  But I guess "this" isn't defined wherever the tests are calling into the library.

The line numbers don't seem right in the exception stack trace, so I'm not really even sure where _log is being accessed.

Wish I knew more about the test framework you've set up, and could help figure out the cause.  Also sorry if one of my commits broke it--I don't see how they could based on when the build started failing, but again, I've never done this before.

**Comment by cmrigney** [comment]
Thanks @ddrinka I'll look into this.

**Comment by cmrigney** [comment]
@ddrinka A recent PR fixed this I believe. Closing.
